

default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 953915
  host: localhost

development:
  <<: *default
  database: Tour_of_Heroes_development


test:
  <<: *default
  database: Tour_of_Heroes_test


#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
production:
  <<: *default
  database: Tour_of_Heroes_production
  username: Tour_of_Heroes
  password: <%= ENV["TOUR_OF_HEROES_DATABASE_PASSWORD"] %>
